
    create table produto (
       id int8 generated by default as identity,
        descricao varchar(255),
        nome varchar(255),
        preco numeric(16, 2),
        sku varchar(255),
        primary key (id)
    );

    create table produto (
       id int8 generated by default as identity,
        descricao varchar(255),
        nome varchar(255),
        preco numeric(16, 2),
        sku varchar(255),
        primary key (id)
    );

    create table produto (
       id int8 generated by default as identity,
        descricao varchar(255),
        nome varchar(255),
        preco numeric(16, 2),
        sku varchar(255),
        primary key (id)
    );

    create table produto (
       id int8 generated by default as identity,
        descricao varchar(255),
        nome varchar(255),
        preco numeric(16, 2),
        sku varchar(255),
        primary key (id)
    );
